/**:
  # Global Parameters
  ros__parameters:
    tf_timeout_threshold: 0.05

    # Set Mavros Plugin Allowlist to explicitly list
    # Which plugins to run! 
    plugin_allowlist:
      - altitude
      - command
      - global_position
      - imu
      - local_position
      - manual_control
      - param
      - rc_io
      - setpoint_attitude
      - setpoint_position
      - setpoint_raw
      - setpoint_velocity
      - sys_status
      - sys_time
      - vision_pose_estimate


/**:
  # Basic Robotics Functions
  # Platform
  platform:
    ros__parameters:
      max_thrust: 29.0
      min_thrust: 0.15
      # # Indoor RealSense
      external_odom: false

  # State Estimator
  state_estimator:
    ros__parameters:
      # Indoor Raw Odometry
      plugin_name: "raw_odometry"
      # # Indoor RealSense
      # plugin_name: "raw_odometry"
      # odom_topic: "sensor_measurements/realsense/odom"
      # # Indoor Motion Capture
      # plugin_name: "mocap_pose"
      # mocap_topic: "/optitrack/rigid_bodies"
      # rigid_body_name: "qav1"
      # twist_smooth_filter_cte: 0.1
      # orientation_smooth_filter_cte: 0.1
      # # Outdoor (GPS) Raw Odometry
      #plugin_name: "raw_odometry"
      #use_gps: true
      #set_origin_on_start: true

  # Behaviors Motion
  TakeoffBehavior:
    ros__parameters:
      # takeoff_plugin_name: "takeoff_plugin_speed"
      takeoff_plugin_name: "takeoff_plugin_position"
      # takeoff_plugin_name: "takeoff_plugin_trajectory"
  LandBehavior:
    ros__parameters:
      land_plugin_name: "land_plugin_speed"
      # land_plugin_name: "land_plugin_trajectory"
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: "go_to_plugin_position"
      # go_to_plugin_name: "go_to_plugin_trajectory"
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: "follow_path_plugin_position"
      # follow_path_plugin_name: "follow_path_plugin_trajectory"

  # Hardware Interfaces
  usb_camera_interface:
    ros__parameters:
      device: "/dev/video0"
      framerate: 30.0 # Frame rate of the camera (fps)
      # Camera configuration
      camera_transform:
        parent_frame: "base_link" # Parent frame of the camera
        x: 0.1 # Translation in x (m)
        y: 0.0 # Translation in y (m)
        z: 0.03 # Translation in z (m)
        roll: -1.57079632679 # Rotation around x (rad)
        pitch: 0.0 # Rotation around y (rad)
        yaw: -1.57079632679 # Rotation around z (rad)

# Specific Parameters for each drone
qav2:
  mavros/mavros_node:
    ros__parameters:
      fcu_url: "serial:///dev/ttyPixhawk" # Autopilot address for connection
      tgt_system: 1 # Target system ID
  
  # Motion Capture
  state_estimator:
    ros__parameters:
      rigid_body_name: "qav2"

# Specific Parameters for each drone
drone0:
  # Platform
  mavros/mavros_node:
    ros__parameters:
      fcu_url: "serial:///dev/ttyUSB0:921600" # Autopilot address for connection
      tgt_system: 1 # Target system ID = Instance + 1

drone1:
  # Platform
  mavros/mavros_node:
    ros__parameters:
      fcu_url: "udp://:14541@127.0.0.1:14558" # Autopilot address for connection
      tgt_system: 2 # Target system ID = Instance + 1

drone2:
  # Platform
  mavros/mavros_node:
    ros__parameters:
      fcu_url: "udp://:14542@127.0.0.1:14559" # Autopilot address for connection
      tgt_system: 3 # Target system ID = Instance + 1
