world_name: "empty"
origin: 
    latitude: 40.4405287
    longitude: -3.6898277
    altitude: 100.0
drones:
  - model_type: "quadrotor_base"
    model_name: "qav1"
    flight_time: 60
    xyz:
      - 0.0
      - 0.0
      - 0.3
    payload:
      - model_type: "gps"
        model_name: "gps"
      - model_type: "gimbal_speed"
        model_name: "gimbal"
        payload:
          model_type: "hd_camera"
          model_name: "camera"
